### ISSUE TITLE
Updated Build Instructions

### ISSUE THREAD

**Issue by MichaelCenger** [kasp1/Dozer#34]
I'm trying to tweak this tool a bit, but the instructions listed under "Build Setup" in the Readme lead to a bunch of errors for me. Are there any updated instructions to get this running? I know the project is old and hasn't been updated in some time, but maybe you can help me out?

**Comment by kasp1** [comment]
Hi @MichaelCenger Thank you for your interest in contributing. :-) You might want to get the latest version which was updated in February. :-) 

What error message do you get when you try the Build Setup commands or where do you get stuck? :-)

**Comment by MichaelCenger** [comment]
To clarify whats happening:

Using the precompiled release works fine for me.
But I want to change some stuff so I cloned the repo and executed (no changes to the code yet):
npm install
npm run dev

npm run dev using only the console works for me. But if I use npm run dev -- ex1.yaml --gui then the gui window opens but doesn't show anything apart from errors in the dev console of the UI 
Errors are: "Uncaught TypeError: Cannot read property 'type' of undefined"
"Uncaught TypeError: Cannot set property 'vars' of undefined"
"TypeError: Cannot read property '$forceUpdate' of undefined"
"Uncaught TypeError: Cannot set property 'steps' of undefined"

So going by the errors the UI cant bind the proper values I guess.

Could it be that I have an incorrect version of node?
Does cloning the project fresh and then following the steps in the Build Setup of the readme, and then running it using the gui flag work for you?

**Comment by kasp1** [comment]
These errors say very little but at first, they would sound to me like you don't have the Electron dependencies installed because if I remember correctly, all the mentioned properties are part of the rendered UI. If you keep being stuck, please feel free to reach to me on Discord Kaspi#0809 ... we can share screen and try to resolve it.

**Comment by kasp1** [comment]
Hi @MichaelCenger I'm just about to release a whole revamp of Dozer (v4). In this version, I made sure to be more descriptive regarding contributions. Please check out the README and kindly let me know your feedback. :-)
